export ISTIO_VERSION="1.4.3"
sudo curl -L https://istio.io/downloadIstio | ISTIO_VERSION=${ISTIO_VERSION} sh -
sudo mv istio-${ISTIO_VERSION}/bin/istioctl /usr/bin/
istioctl verify-install
istioctl manifest apply --set profile=demo

kubectl label namespace default istio-injection=enabled
kubectl get namespace -L istio-injection

cd istio-1.4.3/
kubectl apply -f samples/bookinfo/platform/kube/bookinfo.yaml
kubectl get pods
kubectl get services
kubectl exec -it $(kubectl get pod -l app=ratings -o jsonpath='{.items[0].metadata.name}') -c ratings -- curl productpage:9080/productpage | grep -o "<title>.*</title>"

